server {
    listen 8081 ;
    #host 127.0.0.1;
    host 0.0.0.0;
    server_name cgitest.local;

    client_max_body_size 10485760;

    error_page 400 /errors/400.php;
    error_page 401 /errors/401.php;
    error_page 403 /errors/403.php;
    error_page 404 /errors/404.php;
    error_page 405 /errors/405.php;
    error_page 408 /errors/408.php;
    error_page 413 /errors/413.php;
    error_page 414 /errors/414.php;
    error_page 415 /errors/415.php;
    error_page 500 /errors/500.php;
    error_page 501 /errors/501.php;
    error_page 502 /errors/502.php;
    error_page 503 /errors/503.php;
    error_page 504 /errors/504.php;

    # /, /css, /js, /img, /members, /tools, /errors
    location / {
        root ./www/CGItest;
        index index.php;
        allowed_methods GET POST DELETE;
        autoindex off;
        cgi_extension .php;
        cgi_pass /usr/bin/php-cgi;
    }

    # Uploads
    location /uploads {
        root ./www/CGItest/uploads;
        allowed_methods POST GET DELETE;
        autoindex off;
        upload_path ./www/CGItest/uploads;
    }

    # Redirection
    location /taha{
        return 301 https://www.nyan.cat/index.php?cat=pirate;
    }

    # Python CGI
    location /python {
        root ./www/CGItest/python;
        allowed_methods GET POST;
        autoindex off;
        cgi_extension .py;
        cgi_pass /usr/bin/python3;
    }
}

server {
    listen 9090;
    #host 127.0.0.1;
    host 0.0.0.0;
    server_name cgitested.local;

    client_max_body_size 10485760;

    location / {
        root ./www/other;
        index index.php;
        allowed_methods GET POST DELETE;
        autoindex off;
        cgi_extension .php;
        cgi_pass /usr/bin/php-cgi;
    }
}
