# Testing file

server {
    listen 8080;                        # Required port [3]
    host 127.0.0.1;                     # Required host [3]
    server_name myserver.com;         # Server name (optional but useful)

    # Default error page
    error_page 404 /error_pages/404.html;  # [3]
    error_page 500 /error_pages/500.html;

    # Client body size limit (for uploads)
    client_max_body_size 1024;          # Bytes (or 1M, depending on your parser) [3]

    # Root path / (Default)
    location /home/ {
        root ./www/html;                # Directory where files are stored [3]
        allowed_methods GET POST DELETE;  # Allowed methods [3]
        autoindex on;                   # Directory listing enabled [3]
        index index.html;               # Default file for a directory [3]
        location /user {

        }

    }

    # Path for file uploads
    location /upload {
        root ./www/uploads;
        allowed_methods POST;             # Upload only, no delete or read
        upload_path ./www/uploads;      # Target directory for uploads [3]
        location /pictures {
        }
    }

    # Path for redirection (Bonus/Feature)
    location /old {
        return 301 /new;                # HTTP redirection [3]
    }

    # CGI configuration (scripts)
    location *.php {
        root ./www/scripts;
        cgi_pass ./cgi-bin/php-cgi;     # Executable that processes the script [4]
    }
}

# Second server on another port (Virtual Host)
server {
    listen 9090;
    host 127.0.0.1;
    server_name admin.local;

    location / {
        root ./www/admin;
        allowed_methods GET;
    }
}
